"""Initial migration

Revision ID: 150a8100da12
Revises: 
Create Date: 2021-03-13 17:31:17.379387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150a8100da12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chordnode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_id', sa.String(), nullable=True),
    sa.Column('successor', sa.String(), nullable=True),
    sa.Column('predecessor', sa.String(), nullable=True),
    sa.Column('is_bootstrap', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyvaluepair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chordnode_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('hashed_key', sa.String(), nullable=True),
    sa.Column('replica_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noderecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bootstrap_id', sa.String(), nullable=True),
    sa.Column('ip_port', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noderecord')
    op.drop_table('keyvaluepair')
    op.drop_table('chordnode')
    # ### end Alembic commands ###
