"""Initial migration

Revision ID: 79681945b976
Revises: 
Create Date: 2021-03-10 19:22:42.678168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79681945b976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chordnode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_id', sa.String(), nullable=True),
    sa.Column('successor', sa.String(), nullable=True),
    sa.Column('predecessor', sa.String(), nullable=True),
    sa.Column('is_bootstrap', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyvaluepair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chordnode_id', sa.String(), nullable=True),
    sa.Column('hashed_id', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chordnode_id'], ['chordnode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noderecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bootstrap_id', sa.Integer(), nullable=False),
    sa.Column('ip_port', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bootstrap_id'], ['chordnode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noderecord')
    op.drop_table('keyvaluepair')
    op.drop_table('chordnode')
    # ### end Alembic commands ###
