"""Initial migration

Revision ID: 8e7aa89b6fe0
Revises: 
Create Date: 2021-03-09 00:57:33.226687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7aa89b6fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chordnode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_id', sa.Integer(), nullable=True),
    sa.Column('successor', sa.Integer(), nullable=True),
    sa.Column('predecessor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyvaluepair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chordnode_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chordnode_id'], ['chordnode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyvaluepair')
    op.drop_table('chordnode')
    # ### end Alembic commands ###
